# Generated by Django 4.2.7 on 2023-12-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("idpais", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=8)),
                ("nombre", models.CharField(max_length=30)),
                ("poblacion", models.PositiveBigIntegerField()),
                ("estado", models.CharField(max_length=1)),
            ],
        ),
    ]
